name: flutter_app_builder
description: Build your Flutter app via Dart.
version: 0.0.2
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.0.2
  yaml: ^3.1.0

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker
