name: flutter_distributor
description: Package your Flutter app into OS-specific bundles (.dmg, .exe, etc.) via Dart or the command line.
version: 0.0.2
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.0.2
  app_package_maker_aab: ^0.0.2
  app_package_maker_apk: ^0.0.2
  app_package_maker_deb: ^0.0.2
  app_package_maker_dmg: ^0.0.2
  app_package_maker_exe: ^0.0.2
  app_package_maker_zip: ^0.0.2
  args: ^2.2.0
  flutter_app_builder: ^0.0.2
  flutter_app_packager: ^0.0.2

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker
#   app_package_maker_aab:
#     path: ../app_package_maker_aab
#   app_package_maker_apk:
#     path: ../app_package_maker_apk
#   app_package_maker_deb:
#     path: ../app_package_maker_deb
#   app_package_maker_dmg:
#     path: ../app_package_maker_dmg
#   app_package_maker_exe:
#     path: ../app_package_maker_exe
#   app_package_maker_zip:
#     path: ../app_package_maker_zip
#   app_package_publisher:
#     path: ../app_package_publisher
#   app_package_publisher_fir:
#     path: ../app_package_publisher_fir
#   app_package_publisher_pgyer:
#     path: ../app_package_publisher_pgyer
#   flutter_app_builder:
#     path: ../flutter_app_builder
#   flutter_app_packager:
#     path: ../flutter_app_packager
#   flutter_app_publisher:
#     path: ../flutter_app_publisher

executables:
  flutter_distributor: main
