name: flutter_distributor
description: ""
version: 0.0.1
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.0.1
  args: ^2.2.0
  flutter_app_builder: ^0.0.1
  flutter_app_packager: ^0.0.1
  yaml: ^3.1.0

dependency_overrides:
  app_package_maker:
    path: ../app_package_maker
  app_package_maker_aab:
    path: ../app_package_maker_aab
  app_package_maker_apk:
    path: ../app_package_maker_apk
  app_package_maker_deb:
    path: ../app_package_maker_deb
  app_package_maker_dmg:
    path: ../app_package_maker_dmg
  app_package_maker_exe:
    path: ../app_package_maker_exe
  app_package_maker_zip:
    path: ../app_package_maker_zip
  flutter_app_builder:
    path: ../flutter_app_builder
  flutter_app_packager:
    path: ../flutter_app_packager

executables:
  flutter_distributor: main
