name: app_package_publisher_qiniu
description: Publish your app to qiniu.
version: 0.1.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_publisher: ^0.1.3
  parse_app_package: ^0.1.3
  qiniu_sdk_base: ^0.3.2

# dependency_overrides:
#   app_package_publisher:
#     path: ../app_package_publisher
#   parse_app_package:
#     path: ../parse_app_package