name: app_package_publisher_pgyer
description: Publish your app to pgyer.
version: 0.1.4
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_publisher: ^0.1.4
  dio: ^4.0.4
  parse_app_package: ^0.1.3

# dependency_overrides:
#   app_package_publisher:
#     path: ../app_package_publisher
#   parse_app_package:
#     path: ../parse_app_package
