name: app_package_maker_exe
description: Create a exe package for your app.
version: 0.1.0
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.1.0

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker
