name: app_package_parser
description: App package parser
version: 0.0.3
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  xml: ^5.3.1