name: app_package_maker_deb
description: Create a deb package for your app.
version: 0.0.9
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.0.9

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker
