name: app_package_maker_zip
description: Create a zip package for your app.
version: 0.0.1
homepage: https://github.com/leanflutter/app_package_maker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  app_package_maker: ^0.0.1
  archive: ^3.1.5

# dependency_overrides:
#   app_package_maker:
#     path: ../app_package_maker