name: app_package_maker
description: App package maker
version: 0.0.5
homepage: https://github.com/leanflutter/flutter_distributor

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pub_semver: ^2.1.0
  pubspec_parse: ^1.2.0
  yaml: ^3.1.0
