name: flutter_app_packager
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.2.0
  yaml: ^3.1.0

dependency_overrides:
  app_package_maker:
    path: ../app_package_maker
  app_package_maker_apk:
    path: ../app_package_maker_apk
  app_package_maker_deb:
    path: ../app_package_maker_deb
  app_package_maker_dmg:
    path: ../app_package_maker_dmg
  app_package_maker_exe:
    path: ../app_package_maker_exe
  app_package_maker_zip:
    path: ../app_package_maker_zip

executables:
  flutter_app_packager: main
